export const PROJECTS = [
  {
    num: "01",
    title: "Podvibe",
    img: "/images/Project/RF.png",
    skills: "Node.JS, Tailwind, React Native, TypeScript, Figma",
    description: `A Web Application That enable the user to listen to QURAN and Podcasts about islam and self development 
    and The admin to add the podcasts and handle the website`,
    github: "https://github.com/marwanayman21/PodVibe",
  },
  {
    num: "02",
    title: "M-market",
    img: "/images/Project/M-market.png",
    skills: "React.JS, Tailwind",
    description: `An e-market with different types of categories it has a crud operation, sign in/up functionality, payment stack & search functionality.`,
    github: "https://github.com/marwanayman21/Market",
    web: "https://karim248119.github.io/Martian-Market/",
  },
  {
    num: "03",
    title: "Delivery App",
    img: "/images/Project/delivery.png",
    skills: "React Native",
    description: `A user-friendly mobile delivery app developed using React Native and Expo, focused on providing an intuitive and visually appealing experience for tracking orders and browsing delivery options. This application was designed to showcase seamless navigation and smooth user interactions, making it easy for users to explore available delivery services and monitor their orders in real time.`,
    github: "https://github.com/marwanayman21/Delivery",
  },
  {
    num: "04",
    title: "ANGORA",
    img: "/images/Project/ANGORA.png",
    skills: "HTML, Tailwind, Java Script",
    description: `Simple company landing page`,
    web: "https://karim248119.github.io/ANGORA/",
    github: "https://github.com/marwanayman21/ANGORA",
  },
  {
    num: "05",
    title: "Bakery",
    img: "/images/Project/bakery.png",
    skills: "HTML, CSS, Java Script",
    description: `Simple bakery landing page`,
    web: "https://marwanayman21.github.io/Bakery/",
    github: "https://github.com/marwanayman21/Bakery",
  },
];
